services:
    web:
        image: nginx:1.23
        container_name: nginx-varzea
        ports:
            - "80:80"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        depends_on:
            - php
        networks:
            - varzea
    php:
        build: 
            context: ../
            dockerfile: docker/php/Dockerfile
            target: development
            args:
                USER_ID: ${USER_ID:-0}
                GROUP_ID: ${GROUP_ID:-0}
        image: varzea:latest
        container_name: php-varzea
        networks:
            - varzea
        depends_on:
            postgresqldb:
                condition: service_healthy
    postgresqldb:
        image: postgres:12
        container_name: db-varzea
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        command: -c timezone=America/Sao_Paulo
        volumes:
            - "./data/db:/var/lib/postgresql/data"
        networks:
            - varzea
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"]
            interval: 10s
            timeout: 5s
            retries: 5
    redis:
        image: redis:6.0
        container_name: redis-varzea
        volumes:
            - ./data/redis:/data
        networks:
            - varzea
networks:
    varzea: