version: '3'
services:
    web:
        image: nginx:1.18
        container_name: nginx-varzea
        volumes:
            - "./etc/nginx/gzip.conf:/etc/nginx/conf.d/gzip.conf"
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "../application:/var/www/html"
            - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
        ports:
            - "80:80"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        depends_on:
            - php
            - postgresqldb
        networks:
            - varzea
    php:
        build: 
            context: ../
            dockerfile: docker/php/Dockerfile
        image: docker_varzea/php
        container_name: php-varzea
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "../application:/var/www/html"
        networks:
            - varzea
    postgresqldb:
        image: postgres:12
        container_name: db-varzea
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        command: -c timezone=America/Sao_Paulo
        volumes:
            - "./data/db:/var/lib/postgresql/data"
        networks:
            - varzea
    redis:
        image: redis:6.0
        container_name: redis-varzea
        volumes:
            - ./data/redis:/data
        networks:
            - varzea
networks:
    varzea: