services:
    web:
        volumes:
            - "./etc/nginx/gzip.conf:/etc/nginx/conf.d/gzip.conf"
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "../application:/var/www/html"
            - "./etc/nginx/default.template.certbot.conf:/etc/nginx/conf.d/default.template"
            - certs:/etc/letsencrypt
            - certs-data:/data/letsencrypt
        ports:
            - "80:80"
            - "443:443"
    php:
        image: ${USERNAME}/varzea:latest
volumes:
    certs:
    certs-data:
