version: '3.4'
services:
    web:
        volumes:
            - "./etc/nginx/gzip.conf:/etc/nginx/conf.d/gzip.conf"
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/nginx/default.template.prod.conf:/etc/nginx/conf.d/default.template"
            - certs:/etc/letsencrypt
            - certs-data:/data/letsencrypt
            - application:/var/www/html
        ports:
            - "80:80"
            - "443:443"
    php:
        image: ${USERNAME}/varzea:latest
        container_name: php-varzea
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - application:/var/www/html
            - "../application/.env:/var/www/html/.env"
            - "../application/storage:/var/www/html/storage"
volumes:
    certs:
    certs-data:
    application:
