name: Setup PHP
description: composer install 
runs:
  using: "composite"
  steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: "8.2"
  
    - uses: actions/cache@v3
      with:
        path: /tmp/composer-cache
        key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      
    - uses: php-actions/composer@v6
      with:
        php_version: "8.2"
        command: install -d application
  