name: Certbot renew

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 0'

jobs:
  nuxt:
    name: renew
    runs-on: ubuntu-latest
    steps:
      - name: executing certbot-renew
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_KEY }}
          port: ${{ secrets.AWS_PORT }}
          script: |
            cd varzea
            make certbot-renew