name: Pull Request

on:
  pull_request:

jobs:
  phpstan:
    name: PHPStan Static Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/checkout-application

      - uses: ./.github/actions/setup-php

      - uses: php-actions/phpstan@v3

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [phpstan]

    steps:
      - uses: ./.github/actions/checkout-application

      - uses: ./.github/actions/setup-php

      - run: composer test