name: Pull Request

on:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [phpstan]

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup-php

      - run: composer test
        working-directory: application