name: Deployment workflow

on:
  workflow_dispatch:
  # push:
  #   branches: [main]


jobs:
  nuxt:
    name: Nuxt build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: 'application/.nvmrc'

      - name: Get cache paths
        id: path
        shell: bash
        run: |
          prefix=$(npm prefix --global)
          bin=$(npm bin --global)
          echo "::set-output name=prefix::$prefix"
          echo "::set-output name=bin::$bin"

      - name: Enable cache for packages
        id: cache
        uses: actions/cache@v3 
        with:
          key: ${{ runner.os }}-node-npx-${{ hashFiles('**/package-lock.json') }}
          path: |
            ${{ github.workspace }}/.npm
            ${{ github.workspace }}/node_modules
            ${{ steps.path.outputs.prefix }}/lib/node_modules
            ${{ steps.path.outputs.bin }}

      - name: Install packages
        if: steps.cache.outputs.cache-hit != 'true'
        run: cd application && npm ci

      - name: nuxt-build
        run: cd application && npm run build

      - name: nuxt-generate
        run: cd application && npm run generate

      - name: Upload nuxt build
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            ${{ github.workspace }}/application/public
  
  docker:
    name: Docker build
    runs-on: ubuntu-latest
    needs: nuxt
    steps:
      - uses: actions/checkout@v3

      - name: Download nuxt build
        uses: actions/download-artifact@v3
        with:
          name: build
          path: |
            ${{ github.workspace }}/application/public

      - uses: docker/setup-buildx-action@v2


      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v3
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true
          push: false
          file: docker/php/Dockerfile
          tags: varzea:latest 
      